### ISSUE TITLE
Principe d'Heisenberg dans le cadre relativiste (Chap1)

### ISSUE THREAD

**Issue by AnaisDefossez** [jmoeil/PHYS-F203#5]
J'ai eu du mal à expliquer la longueur d'onde de Compton donc j'avoue que je suis pas trop sûre de ce que j'ai écrit, n'hésitez pas à faire un check!

Sinon sur Internet, on définit la longueur de Compton de 2 façon, d'une part dans la diffusion de Compton, et d'autre part avec l'incertitude d'Heisenberg comme j'ai fait, mais est-ce que vous voyez le lien entre les 2 manières dont elle est définie?

**Comment by jemappellesami** [comment]
Dans mon cours de Physique Quantique de BA2 (PHYS-H200) on a justement abordé la longueur d'onde Compton dans le cadre de l'effet Compton. Voici ce qui est dit à ce sujet : 
![image](https://user-images.githubusercontent.com/44751925/124923619-e8791700-dffa-11eb-9abc-fd96d739de45.png)

Je concluerais que cette longueur est une longueur caractéristique pour une particule, et qui intervient dans plusieurs propriétés physiques, comme ici la dimension d'une boite suffisante pour que d'un électron relativiste il puisse y avoir une incertitude sur l'énergie telle qu'une paire de particules peut être créée ; ou le coefficient de proportionnalité du déplacement lors de la diffusion Compton (voir photo), etc.

Qu'en pensez-vous ? on pourrait s'amuser à chercher d'autres cas où la longueur d'onde de Compton invervient
